import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Manager!
        </h1>

        <p className={styles.description}>
          This will (eventually) be awesome :)
        </p>
      </main>

      <footer className={styles.footer}>
        <a>
          Powered by Me {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
